### PR TITLE
Docker file is added

### PR DESCRIPTION
**Pull request by shraddha761**
# Related Issues
#407 
  
# Proposed Changes
I have added an docker file which sets up an Nginx server in a container, copies an index.html file and a static directory to serve as static assets, exposes port 80, and starts the Nginx server when the container is launched.
  
# Additional Information
- Any additional information or context
  
# Checklist
- [x] Tests
- [ ] Translations
- [ ] Documentations

### CODE REVIEW

**Comment by AnirudhPanda** [comment]
Please update the readme too for users who are unaware of it

**Comment by shraddha761** [comment]
@AnirudhPanda I have updated the readme

**Comment by AnirudhPanda** [comment]
Hey @shraddha761 can you please join https://chat.whatsapp.com/C4gcudkI8o0EriFlKcHWIY and drop a HI

many have doubts regarding docker thing

**Comment by shraddha761** [comment]
@AnirudhPanda Yahh sure

**Pull request merged**
