### PR TITLE
New program added

### PR DESCRIPTION
**Pull request by prakhar728**
# Related Issues
- Add more OPEN SOURCE programs and events
  
# Proposed Changes
- Add MLH Open Source Tracks in programs
- Solving issue #69 

# Screenshots

Original             |  Updated
:-------------------------:|:-------------------------:
Screenshot from 2021-10-01 11-07-33|  Screenshot from 2021-10-01 11-07-47

### CODE REVIEW

**Comment by AnirudhPanda** [comment]
Hey, @prakhar728 you need to add it only once the month the program is going to start!
Update the same and I will merge the PR

**Comment by prakhar728** [comment]
> Hey, @prakhar728 you need to add it only once the month the program is going to start! Update the same and I will merge the PR

Can you checkout now?

**Comment by AnirudhPanda** [comment]
> > Hey, @prakhar728 you need to add it only once the month the program is going to start! Update the same and I will merge the PR
> 
> Can you checkout now?

I meant add just in one month
Not all 3 is required

**Comment by prakhar728** [comment]
> > > Hey, @prakhar728 you need to add it only once the month the program is going to start! Update the same and I will merge the PR
> > 
> > 
> > Can you checkout now?
> 
> I meant add just in one month Not all 3 is required

Actually it runs thrice a year. So I added 3 times. If you want I can write only once or change the names of the batch(spring,summer, and fall)

**Comment by AnirudhPanda** [comment]
> > > > Hey, @prakhar728 you need to add it only once the month the program is going to start! Update the same and I will merge the PR
> > > 
> > > 
> > > Can you checkout now?
> > 
> > 
> > I meant add just in one month Not all 3 is required
> 
> Actually it runs thrice a year. So I added 3 times. If you want I can write only once or change the names of the batch(spring,summer, and fall)

But you mentioned spring batch in all the 3

**Comment by prakhar728** [comment]
> > > > > Hey, @prakhar728 you need to add it only once the month the program is going to start! Update the same and I will merge the PR
> > > > 
> > > > 
> > > > Can you checkout now?
> > > 
> > > 
> > > I meant add just in one month Not all 3 is required
> > 
> > 
> > Actually it runs thrice a year. So I added 3 times. If you want I can write only once or change the names of the batch(spring,summer, and fall)
> 
> But you mentioned spring batch in all the 3

Now? It must be fixed

**Pull request merged**
