### PR TITLE
copy right footer

### PR DESCRIPTION
**Pull request by Sushilverma002**
# Related Issues
CLOSE-> #287   
# Proposed Changes
- Change 1
- Change 2
  
# Additional Information
- Any additional information or context
  
# Checklist
- [X] Tests
- [X] Translations
- [X] Documentations

# Screenshots
image

Original             |  Updated
:-------------------------:|:-------------------------:
** Original Screenshot **  |  ** Updated Screenshot **

### CODE REVIEW

**Comment by AnirudhPanda** [comment]
is this is the correct format @Sushilverma002 

cc: @sunny0625

**Comment by Sushilverma002** [comment]
Is this correct or should I have to make changes i read your licence and from there I took info @AnirudhPanda

**Comment by AnirudhPanda** [comment]
I guess present year is needed
cc: @sunny0625 please do the research

**Comment by Sushilverma002** [comment]
image
@sunny0625 @AnirudhPanda see in your license the year is 2021 is mention that's why i write. please approve and merge. 
ty:)

**Comment by sunny0625** [comment]
> I guess present year is needed
> cc: @sunny0625 please do the research

Yeah present year needed

**Comment by Sushilverma002** [comment]
image
updated please review and merge

**Pull request merged**
