### PR TITLE
chore: Added Linkedin Clone

### PR DESCRIPTION
**Pull request by SyedImtiyaz-1**
Issue No. #585 

### Description 
Hello @AnirudhPanda ,
Added a Linkedin Clone Using HTML, CSS, JS
Please review it.
  
# Additional Information
- Any additional information or context
  
# Checklist
- [x] Terms & Policy

# Screenshots
Screenshot from 2023-08-03 11-55-39

### CODE REVIEW

**Comment by AnirudhPanda** [comment]
Resolve conflicts

**Comment by SyedImtiyaz-1** [comment]
@AnirudhPanda Conflicts Resolved.

**Comment by AnirudhPanda** [comment]
code kahan h

**Comment by SyedImtiyaz-1** [comment]
@AnirudhPanda Now visible 👍🏻 
image

**Pull request merged**
