### PR TITLE
updated style.css

### PR DESCRIPTION
**Pull request by Swati002**
# Related Issues
- #125
  
# Github Page Link
 https://swati002.github.io/opentek/
  
# Additional Information
- Removed texture line from header
  
# Checklist
- [ ] Tests
- [ ] Translations
- [ ] Documentations

# Screenshots

Original             |  Updated
:-------------------------:|:-------------------------:
** Original Screenshot ** image |  ** Updated Screenshot **   

image

### CODE REVIEW

**Comment by Swati002** [comment]
#125 resolved. Please check @nileshkr17

**Comment by nileshkr17** [comment]
> #125 resolved. Please check @nileshkr17

Can add updated screenshot.

**Comment by Swati002** [comment]
> 

Added updated screenshot. Please check! @nileshkr17

**Comment by Swati002** [comment]
image
Updated one @nileshkr17 
Removed texture line from header

**Comment by Swati002** [comment]
@nileshkr17 Please check!

**Comment by nileshkr17** [comment]
@Swati002 🎉

**Pull request merged**
