### PR TITLE
Added Discord Banner at the Top of HomePage

### PR DESCRIPTION
**Pull request by PrafulAnand**
# Related Issues
- https://github.com/Opentek-Org/opentek/issues/42
  
# Proposed Changes
- Added discord banner element before the nav bar
- Added styles for the same in styles.css
  
# Additional Information
- N/A
  
# Checklist
- [ ] Tests
- [ ] Translations
- [ ] Documentations

# Screenshots

Original ScreenShot
:-------------------------:|:-------------------------:
image

Updated ScreenShot
:-------------------------:|:-------------------------:
image  **

### CODE REVIEW

**Comment by AnirudhPanda** [comment]
We should decrease the padding in the #banner id so that the banner text appear at center

**Comment by PrafulAnand** [comment]
@AnirudhPanda  padding top: 200px is it fine ?

**Comment by AnirudhPanda** [comment]
> @AnirudhPanda padding top: 200px is it fine ? Also can you post a snap , so that i can refer to the issue which you mentioned , as at the first glance the landing page is looking fine to me

We can do one thing!

Push this into `admin` branch and I will see to it

**Comment by PrafulAnand** [comment]
> > @AnirudhPanda padding top: 200px is it fine ? Also can you post a snap , so that i can refer to the issue which you mentioned , as at the first glance the landing page is looking fine to me
> 
> We can do one thing!
> 
> Push this into `admin` branch and I will see to it

so i should raise a pr against admin branch or  can i directly push it ?

**Comment by AnirudhPanda** [comment]
> > > @AnirudhPanda padding top: 200px is it fine ? Also can you post a snap , so that i can refer to the issue which you mentioned , as at the first glance the landing page is looking fine to me
> > 
> > 
> > We can do one thing!
> > Push this into `admin` branch and I will see to it
> 
> so i should raise a pr against admin branch or can i directly push it ?

push it

**Comment by PrafulAnand** [comment]
closing the PR as the changes would be going from admin branch

**Pull request closed without merging**
