### PR TITLE
Grammar

### PR DESCRIPTION
**Pull request by MuditWadhwa**
I have tried my best to correct all grammatical errors and have done suitable commits in multiple files to demonstrate the same. Please review them. Merging this PR successfully would solve the issue #79.

### CODE REVIEW

**Comment by AnirudhPanda** [comment]
> Hey there! 👋 This repository uses the [Prettier](https://prettier.io) code style.
> 
> You forgot to format these files in your pull request:
> 
> * index.html
> * js/event.js
> * js/projects.js
> 
> The [Prettier installation guide](https://prettier.io/docs/en/install.html) is a good place to get started with formatting your code properly. Thanks!
> 
> ❤️
> 
> Your friendly [Prettifier bot](https://www.prettifier.io).

Great Work @MuditWadhwa 

Would you format the mentioned files! After this I will merge the PR

**Comment by MuditWadhwa** [comment]
I have used prettifier and pushed on the same branch again. Please check if you got it.

**Comment by AnirudhPanda** [comment]
Hey, there are a lot of new changes in here!
@MuditWadhwa 

If possible create a new PR

**Comment by MuditWadhwa** [comment]
Any specific instructions regarding the new PR? Like anything to keep in in mind so that it merges well...Shall I do it from a new branch

**Comment by MuditWadhwa** [comment]
I am new to prettier..Hence,there were a lot of changes

**Comment by AnirudhPanda** [comment]
> Any specific instructions regarding the new PR? Like anything to keep in in mind so that it merges well...Shall I do it from a new branch

Install Prettier
Follow instructions here and you are good to go https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode

**Comment by MuditWadhwa** [comment]
I have already installed it and formatted files using it.....Anything else that should be done to make things better!

**Pull request closed without merging**
