### PR TITLE
Added transition effects in the about section

### PR DESCRIPTION
**Pull request by Illaf**

### CODE REVIEW

**Comment by AnirudhPanda** [comment]
can you apply the same on the ABOUT page in this PR itself?

**Comment by Illaf** [comment]
> can you apply the same on the ABOUT page in this PR itself?

Can you please elaborate? I have applied the effects in the about page only. Do you want to add effects in the about heading?

**Comment by Illaf** [comment]
@AnirudhPanda no in this one 

If you want ,I will add effects in about us page as well

**Comment by AnirudhPanda** [comment]
> @AnirudhPanda no in this one  If you want ,I will add effects in about us page as well

yeah please do

**Comment by Illaf** [comment]
@AnirudhPanda It seems that aos library is currently facing some problem or broken issues. If the problem persists , I will add animations through css .
Meanwhile if you could merge this pr so that i can avoid merge conflicts

**Pull request merged**
