### PR TITLE
Changed style.css

### PR DESCRIPTION
**Pull request by Swati002**
# Related Issues
- Removed texture line from the header
  
# Proposed Changes
- Change 1
- Change 2
  
# Additional Information
- Any additional information or context
  
# Checklist
- [ ] Tests
- [ ] Translations
- [ ] Documentations

# Screenshots

Original             |  Updated
:-------------------------:|:-------------------------:
** Original Screenshot **  |  ** Updated Screenshot **

### CODE REVIEW

**Comment by Swati002** [comment]
@AnirudhPanda

**Comment by Swati002** [comment]
#125 issue resolved. Please check @nileshkr17

**Comment by nileshkr17** [comment]
@Swati002 You'll need to update your branch with new commits from main, resolve those conflicts and push the updated/resolved branch to main.

**Comment by Swati002** [comment]
``

**Pull request closed without merging**
