### PR TITLE
Updated Footer alignment

### PR DESCRIPTION
**Pull request by aman-kumar29**
#449 
# Related Issues
- The footer's alignment is not proper for different screen sizes. (not responsive)
  
# Proposed Changes
- I made it centrally aligned when the screen size dropped below a certain size (767 px)
  
# Additional Information
- Any additional information or context
  
# Checklist
- [x] Tests
- [x] Translations
- [x] Documentations

# Screenshots

Original             |  Updated
:----
prev  |  
next

### CODE REVIEW

**Comment by AnirudhPanda** [comment]
image
this looks odd to me

**Comment by AnirudhPanda** [comment]
> image this looks odd to me

@aman-kumar29 are you working on this or shall I assign this issue to someone else?

**Comment by aman-kumar29** [comment]
hello @AnirudhPanda I am working on it.

**Comment by aman-kumar29** [comment]
@AnirudhPanda I have the changes now. I'd like you to go through it and tell me if it's alright.

**Comment by AnirudhPanda** [comment]
did you make the change on all the pages? @aman-kumar29

**Comment by aman-kumar29** [comment]
Yes!

**Pull request merged**
