### PR TITLE
Add Community Partners section in README.md

### PR DESCRIPTION
**Pull request by siddhant94**
# Related Issues
#95 
  
# Proposed Changes
- Add "Community Partners" section
  
# Screenshots

Original             |  Updated
:-------------------------:|:-------------------------:
** Original Screenshot **  |  ** Updated Screenshot **
Screenshot from 2021-10-29 16-29-59 |  Screenshot from 2021-10-29 16-30-50

### CODE REVIEW

**Comment by AnirudhPanda** [comment]
Any Updates? @siddhant94

**Comment by siddhant94** [comment]
> Any Updates? @siddhant94

Can you help in getting what images you want? Just the logo of something else? And if images(svg/png), where should I upload them or it should directly link to their website? For techsahead icc, there is a png and for mlh guild and swoc svg's are there. Let me know the way forward.

**Comment by AnirudhPanda** [comment]
> > Any Updates? @siddhant94
> 
> Can you help in getting what images you want? Just the logo of something else? And if images(svg/png), where should I upload them or it should directly link to their website? For techsahead icc, there is a png and for mlh guild and swoc svg's are there. Let me know the way forward.

You can convert them into single format

**Comment by siddhant94** [comment]
But where do you host these "converted" assets to link them in Readme?

**Pull request closed without merging**
