### PR TITLE
hovering is personalized according to each  social icons

### PR DESCRIPTION
**Pull request by Tarun0951**
# Proposed Changes
hover effects are personalized according to each social icon. The background color of the tooltips  and icons change to match the respective brand colors. This creates a more cohesive and relevant hover experience for the social icons in the footer.
  

# Sample Screenshots

Original             |  Updated
:-------------------------:|:-------------------------:
** Original Screenshot **  |  ** Updated Screenshot **
image 
image
                                   
        
image
image

### CODE REVIEW

**Comment by AnirudhPanda** [comment]
@sunny0625 is this gtg?

**Comment by Tarun0951** [comment]
> @sunny0625 is this gtg?

What?

**Comment by sunny0625** [comment]
> @sunny0625 is this gtg?

Yeah, Looks better!

**Comment by sunny0625** [comment]
> @sunny0625 is this gtg?

IDTS we should add text or any other details. Symbols are already saying all!

**Comment by sunny0625** [comment]
Closing this issue!

**Comment by sunny0625** [comment]
> @AnirudhPanda @sunny0625 this isn't fair and completely against to contributing guidelines you assigned me and that was clearly mentioned in the demo in my issue but now you closed it

Apologies for the inconvenience caused by us. I try checking your issue in Detail.
Can you plz confirm your issue no? #???

**Comment by Tarun0951** [comment]
#227

**Pull request closed without merging**
