### PR TITLE
Feat: Multiple Filters at a time.

### PR DESCRIPTION
**Pull request by kailashchoudhary11**
Features Implemented:
1.) The User can toggle a filter by clicking on it. That is if the filter is already selected it will get deselected and if the filter is not selected then it will be selected on click.
2.) The User can select more than one filter at a time.
3.) Removed the All button from filters since all the projects will be visible if none of the filter is selected.

### CODE REVIEW

**Review by AnirudhPanda — COMMENTED** [review]
keep the All filter. Looks complete. Also would need a little message that multiple can be selected

**Comment by kailashchoudhary11** [comment]
@AnirudhPanda Added a `clear filters` button. The button will only be visible whenever the user selects filters. On clicking the clear filter button, all the filters will be deselected and the clear filter button will be hidden.

**Comment by kailashchoudhary11** [comment]
@AnirudhPanda I've resolve the conflicts kindly review

**Comment by AnirudhPanda** [comment]
merge conflicts @kailashchoudhary11

**Comment by kailashchoudhary11** [comment]
> merge conflicts @kailashchoudhary11

bro aise tum mere pehle baaki PRs ko merge karte rahoge to conflicts aate hee rahenge na :)

**Comment by kailashchoudhary11** [comment]
@AnirudhPanda I've resolved review now

**Comment by AnirudhPanda** [comment]
BRO LAST TIME PROMISEEE!!

**Comment by AnirudhPanda** [comment]
broooo @kailashchoudhary11

**Pull request closed without merging**
