### PR TITLE
[fix] The feature part hidden on large screens.

### PR DESCRIPTION
**Pull request by vedikamujgule**
# Related Issues
Description
The feature part should not be visible when the page is loaded.

AN OPEN SOURCE TREASURE

  
# Proposed Changes
If it is about Open Source, it is on Opentek.

Should be visible on the first load screen.
  
# Screenshots

Original             |  Updated
:-------------------------:|:-------------------------:
image  |image

### CODE REVIEW

**Comment by vedikamujgule** [comment]
image

**Comment by manavdesai27** [comment]
@vedikamujgule In smaller screen size doesn't it look a little too down from the top?

**Comment by vedikamujgule** [comment]
Please review the code

**Comment by vedikamujgule** [comment]
@AnirudhPanda any issue with this PR yet to be resolved?

**Pull request merged**
