### PR TITLE
Added Community Partners section with images

### PR DESCRIPTION
**Pull request by iArchitSharma**
# Screenshots

This is how it looks
Screenshot updated

### CODE REVIEW

**Comment by nileshkr17** [comment]
Hey @iArchitSharma 😄,
Could you add border radius or something to it and size is not uniform.
ref: https://github.com/smaranjitghose/awesome-portfolio-websites#open-source-programs-we-have-been-a-part-of

**Comment by iArchitSharma** [comment]
> Hey @iArchitSharma 😄, Could you add border radius or something to it and size is not uniform. ref: https://github.com/smaranjitghose/awesome-portfolio-websites#open-source-programs-we-have-been-a-part-of

ok sure, let me work on it

**Comment by iArchitSharma** [comment]
Hey @nileshkr17  ,
Check it now it looks better I  guess

**Comment by nileshkr17** [comment]
@iArchitSharma Can you update screenshot, because I am not able to find any changes in it.

**Comment by nileshkr17** [comment]
Also would you like to work on #94 ?
@iArchitSharma

**Comment by iArchitSharma** [comment]
> @iArchitSharma Can you update screenshot, because I am not able to find any changes in it.

Here is the screenshot :
Screenshot (17)

**Comment by iArchitSharma** [comment]
> Also would you like to work on #94 ? @iArchitSharma

Hey I would love to work on this issue

**Pull request merged**
