### PR TITLE
 [Mobile] Navbar Styling-[hamburger-to-cross]

### PR DESCRIPTION
**Pull request by nileshkr17**
# Related Issues
- issue goes here
  
# Proposed Changes
- Change 1
- Change 2
  
# Additional Information
- Any additional information or context
  
# Checklist
- [x] Tests
- [x] Translations
- [x] Documentations

# Screenshots

Original             |  Updated
:-------------------------:|:-------------------------:
** Original Screenshot **  |

131460575-ad1884ab-d26d-43f3-a033-86b5b4550e2e

|  ** Updated Screenshot **

image

### CODE REVIEW

**Comment by AnirudhPanda** [comment]
Great Work @nileshkr17 
Can you think of anything that could make the navbar in MOBILE look good? something like border radius?

**Comment by nileshkr17** [comment]
> Great Work @nileshkr17
> Can you think of anything that could make the navbar in MOBILE look good? something like border radius?

Sure!

**Comment by AnirudhPanda** [comment]
> > Great Work @nileshkr17
> > Can you think of anything that could make the navbar in MOBILE look good? something like border radius?
> 
> Sure!

Any updates @nileshkr17 ?

**Comment by nileshkr17** [comment]
> > > Great Work @nileshkr17
> > > Can you think of anything that could make the navbar in MOBILE look good? something like border radius?
> > 
> > 
> > Sure!
> 
> Any updates @nileshkr17

**Comment by nileshkr17** [comment]
> > > > Great Work @nileshkr17
> > > > Can you think of anything that could make the navbar in MOBILE look good? something like border radius?
> > > 
> > > 
> > > Sure!
> > 
> > 
> > Any updates @nileshkr17

**Comment by nileshkr17** [comment]
** Original Screenshot **
134901141-c5f36b28-804b-4c1d-aa0e-28793cc65a21

** Updated Screenshot **
image

**Comment by AnirudhPanda** [comment]
> ** Original Screenshot ** 134901141-c5f36b28-804b-4c1d-aa0e-28793cc65a21
> 
> ** Updated Screenshot ** image

Looks good!

**Comment by AnirudhPanda** [comment]
Great Work @nileshkr17 🎉
Closes #23

**Pull request merged**
